# Generated by Django 4.1.7 on 2023-08-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_followers_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
