version: '3.9'

services: 
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  web:
    build: .
    command: >
      sh -c "python manage.py wait__for__db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
             
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db